# config file
tcl: "inputs/directives.tcl"
includes: "inputs/sampler_falcon_preprocessed/sampler_inc.txt"
orig_code: "inputs/sampler_falcon_preprocessed/sampler.txt"
test_code: "inputs/sampler_falcon_preprocessed/sampler_test.c"
top_function: "sampler"