# config file
tcl: "inputs/directives.tcl"
includes: "inputs/samplerz_falcon/samplerz_inc.txt"
orig_code: "inputs/samplerz_falcon/samplerz.txt"
test_code: "inputs/samplerz_falcon/samplerz_test.c"
top_function: "sampler"
hierarchical: True