# config file
tcl: "inputs/directives.tcl"
includes: "inputs/fft_falcon/fft_inc.txt"
orig_code: "inputs/fft_falcon/fft_original.c"
test_code: "inputs/fft_falcon/fft_test.txt"
kat_file: "inputs/fft_falcon/fft_kat_vectors.txt"
top_function: "falcon_FFT"
# hierarchical: True