# config file
tcl: "inputs/directives.tcl"
includes: "inputs/ntt_kyber/ntt_inc.txt"
orig_code: "inputs/ntt_kyber/ntt.txt"
test_code: "inputs/ntt_kyber/ntt_test.txt"
top_function: "montgomery_reduce"

