# config file
tcl: "inputs/directives.tcl"
includes: "inputs/ntt_kyber_hierarcy/ntt_inc.txt"
orig_code: "inputs/ntt_kyber_hierarcy/ntt.txt"
test_code: "inputs/ntt_kyber_hierarcy/ntt_test.c"
top_function: "ntt"
hierarchical: True
