# config file
tcl: "inputs/directives.tcl"
includes: "inputs/sampler_falcon/sampler_inc.txt"
orig_code: "inputs/sampler_falcon/sampler.txt"
test_code: "inputs/sampler_falcon/sampler_test.c"
top_function: "sampler"
# hierarchical: True