# config file
tcl: "inputs/directives.tcl"
includes: "inputs/samplerz_falcon_non_hierarcy/samplerz_inc.txt"
orig_code: "inputs/samplerz_falcon_non_hierarcy/samplerz.txt"
test_code: "inputs/samplerz_falcon_non_hierarcy/samplerz_test.c"
top_function: "sampler"